### PR TITLE
Fix sum of issues

### PR DESCRIPTION
**Pull request by matheusfm**
## Description
This PR fixes the sum of issues for misconfiguration scans.
A scan was being unnecessarily append into a slice with all scans. 
This slice always has the updated version of all scans.

## How has this been tested?
Configuring a misconfiguration scan and looking at `issueCount` field in ClusterScan status. It was always with the double.

## Checklist
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

### CODE REVIEW

**Review by knrc — APPROVED** [review]

**Review by knrc — COMMENTED** [review]
Looks like this is reverting an earlier fix for stale information, this needs thinking about

**Comment by knrc** [comment]
> Looks like this is reverting an earlier fix for stale information, this needs thinking about

Yes, it looks as if we are re-introducing the previous bug.  I suspect the real fix would be to remove the current cluster scan information from the map of scans, rather than revert the previous bug fix.

**Review by knrc — CHANGES_REQUESTED** [review]
The fix needs for the sums needs to be reworked as it reintroduces the issue of stale data.  The correct fix is likely removing the current cluster scan information from the map of scans, but needs to be tested.

**Comment by matheusfm** [comment]
Thank you, @knrc 
I'll take a look at the issue of stale data.

**Comment by matheusfm** [comment]
Here is the PR from the mentioned fix of stale information: https://github.com/undistro/zora/pull/237

**Comment by matheusfm** [comment]
@knrc 
I've created unit test for this function with a case that would fail for both current code (due to `IssueCount` field) and first version of this PR (due to stale scan ID).
I also have updated the fix to ensure ensure a ClusterScan is not processed twice, which passes in the unit test.

**Review by knrc — APPROVED** [review]

**Pull request merged**
